### PR TITLE
Issue 13 rect

### LINKED ISSUE #13: plot: make Rect work the same way as image.Rectangle
image.Rectangle keeps to points, Min and Max and calculates Size from those. plot.Rect keeps a Min and a Size and calculates Max from those. It would be nice to have the two types speak with a similar accent.

Raised [here](https://github.com/sbinet/gonum-plot/commit/6c810295adb4dd7fa1233526d7a4b35f9f69de6f#commitcomment-9691115).

### PR DESCRIPTION
**Pull request by sbinet**
- make `vg/draw.Rect` a `Rectangle{Min,Max Point}`
- fixes #13

### CODE REVIEW

**Comment by kortschak** [comment]
Please wait for #7 to be reviewed so that people can comment on that in action.

**Comment by kortschak** [comment]
LGTM

**Comment by kortschak** [comment]
This will need to now include the Contour and HeatMap plotters. Sorry.

**Comment by sbinet** [comment]
yep, already rebased.

**Comment by kortschak** [comment]
LGTM

Please squash to one commit.

**Comment by sbinet** [comment]
done.

**Pull request merged**
