### PR TITLE
vg/vgpdf: export Canvas.EmbedFonts

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
after a good night sleep on this, I am wondering whether we shouldn't unexport the field and instead provide a method to modify it.

then, other canvas backend could also implement that `FontEmbedder` interface: obvious other implementer (I think): the PostScript canvas.

well, I can only think of these 2 canvas (PDF, PS) so perhaps it's not general enough to derive and implement an interface... WDYT?

**Comment by sbinet** [comment]
PTAL: I went with the method instead with exposing the field.

@kortschak let me know if you prefer that way or the previous one.

**Comment by kortschak** [comment]
Either of these is fine - I don't have any strong feelings eitherway - though possibly the method is better.

**Comment by sbinet** [comment]
PTAL @kortschak 
(the test failure is unrelated, but I don't understand why it suddenly appeared... we should perhaps add a cron/scheduled build to catch these)

**Comment by sbinet** [comment]
I've filed #448 for the test failure.

**Pull request merged**
