### PR TITLE
Add link to Community Plotters page in README.md

### PR DESCRIPTION
**Pull request by eaburns**

### CODE REVIEW

**Comment by sbinet** [comment]
LGTM

**Comment by eaburns** [comment]
Travis is sad, but it's certainly not because of this PR.

**Comment by sbinet** [comment]
yeah... maybe another draw2d commit?

**Comment by eaburns** [comment]
That's quite annoying. I'm wondering if we should vendor the dependencies, but the recommendation seems to be that vendoring should happen only for binary packages. Do we ignore that advice? Can anyone think of a better solution?

**Comment by eaburns** [comment]
Maybe we can configure travis to pull particular commits for each dependency. That way, binary packages pulling gonum/plot don't get blocked by our internal vendoring, but we can still test to know upstream versions.

**Pull request merged**
