### PR TITLE
vg/vg{img,pdf}: do not display text with zero font size

### PR DESCRIPTION
**Pull request by sbinet**
Fixes gonum/plot#540.

### CODE REVIEW

**Comment by ctessum** [comment]
Maybe rebase onto master after the other changes are merged? It is difficult to see which changes are specific to this PR

**Comment by sbinet** [comment]
right. will do :)

**Comment by sbinet** [comment]
done. PTAL.

**Comment by ctessum** [comment]
Great. Looks good to me, except one question: is this feature documented anywhere?

**Comment by kortschak** [comment]
Maybe another PR to add documentation that zero size is a general purpose approach to not showing a thing with size (unfilled lines as well).

**Pull request merged**
