### PR TITLE
plotter: add colour magnitude vector field example

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
... and now in the correct PR.

I'm thinking also that maybe `DrawGlyph` should take a `draw.LineStyle`. This would mean that the function does not need to be a closure and we can provide a set of them (or others can). WDYT?

**Comment by chewxy** [comment]
Is the `draw.LineStyle`  such that a pre-specified linestyle may be passed onto the `DrawGlyph` function? Chances are people are gonna write custom `DrawGlyph` functions anyway... but I suppose it may be a nice option to have a default `DrawGlyph` function, then you just pass in the `LineStyle`

**Comment by kortschak** [comment]
Yes, that was my thinking. If we have common arrows, coloured arrows etc, that would be helpful. Otherwise we need constructors to insert the style into a closure.

I'll push what I have here.

**Comment by kortschak** [comment]
PTAL

**Comment by kortschak** [comment]
*ping*

**Comment by chewxy** [comment]
The default DrawGlyph function is not in yet?

**Comment by kortschak** [comment]
It `DrawGlyph` is nil `Field` uses `drawVector`.

**Pull request merged**
