### PR TITLE
git: migrate hg ignore file to git

### PR DESCRIPTION
**Pull request by sbinet**
- remove last remnant of mercurial past life
- adapt to gitignore syntax

### CODE REVIEW

**Comment by sbinet** [comment]
ping?

**Comment by eaburns** [comment]
I'm not familiar with the gitignore matching syntax, but if no one else will say it, LGTM.

**Comment by sbinet** [comment]
just for future reference:
 http://git-scm.com/docs/gitignore

**Comment by eaburns** [comment]
Thanks. Sorry, I'd have looked it up myself but I was on my phone on the subway :-)

**Pull request merged**
