### PR TITLE
Adds capability for colored scatter plots (#195), Palette.Thumbnails option (#396)

### PR DESCRIPTION
**Pull request by Scorpiokat**
Rebase master failed, so I decided to send a new PR instead. Hope that works better. @kortschak 
Should I make a separate commit with a ColorBar? @ctessum

### CODE REVIEW

**Comment by kortschak** [comment]
I'm not sure that this is the best approach. We do keep the history of the previous review, but we also need to re-read that in the context of this to know what decisions were made there. It is some work to resolve conflicts, but you would be surprised at how little that sometimes is; I just tried the squash and rebase onto master (and the rebase onto master first as an alternative strategy). There is no conflict when the commits are first merged. This paradoxical behaviour comes about because some of the conflicting commits revert out in the interactive rebase and so have never happened by the time you rebase onto master.

What I did (on a checkout of your newfeature\* branch):

```
$ rebase -i HEAD~25 # work on the last 25 commits of the branch
```

In the editor, I changes the 2-24 lines from 'pick' to 'squash' and the last line to 'edit' and then quit. I edited commit messages to match the convention (resulting in the log below) at the prompts
Then on completion of the interactive rebase I had 2 clean commits and tried to rebase onto master; after pulling the local master to be up to date with gonum/plot master:

```
git rebase master
```

This completed successfully giving me this:

```
commit aa06f5559ab7bab8fe436740d7987a38f504b90b
Author: Scorpiokat <katerina.efimova@gmail.com>
Date:   Tue Nov 21 06:23:07 2017 +0300

    plotter: revert ColorBar to PaletteThumbnailers

commit 013505f314e26247dbf177763f24dabe5c50cf92
Author: Scorpiokat <katerina.efimova@gmail.com>
Date:   Sat Oct 7 17:17:04 2017 +0300

    plotter: add colored scatter plots

commit d0829a180c0d6829c8c11539648663964780ff39
Author: kortschak <dan.kortschak@adelaide.edu.au>
Date:   Wed Nov 22 11:07:38 2017 +1030

    internal/cmpimg: add image diffing output
...
```

Note that this has a linear history, with no extraneous merge commits (this make thinking about the history easier) and also has clearer commit messages.

Would you please try this on your branch. I'm happy to help you in the process, but it's pretty straight forward (and something that is worth knowing how to do - you should at some point practice with resolving commit conflicts too, but leave that for later).

Finally, I'd strongly recommend against sending PR from a master branch, since it only results in pain later on for you.

**Comment by kortschak** [comment]
BTW, during a rebase (interactive or otherwise), if it all goes wrong before completion (i.e. it does not succeed), you can `git rebase --abort` and you will be returned to the state prior to starting the rebase. Also, if you don't like the outcome, you can always just `git reset --hard <commit>` where the commit is the original state (either by tag, branch or sha-1 - you can take note of the sha-1 before starting or just so `git reset --hard origin/newfeature` in this case assuming your local repo point to `https://github.com/Scorpiokat/plot.git` as `origin`).

**Comment by Scorpiokat** [comment]
Dan thank you so much for the guidance. I do really appreciate your help and will carefully follow the instructions.
May I ask - should I close this PR and manually change the forked master branch? Or how to change the master branch back to the previous state, so that I can do all these manipulations from the newfeature branch?

**Comment by kortschak** [comment]
The two issues are entirely independent. What I would do fetch gonum/plot master and reset your master to that with `--hard`, then add gonum/plot master as a tracked remote ([this](https://stackoverflow.com/questions/11262703/track-a-new-remote-branch-created-on-github) shows how to do that). If you name that remote gonum, then when you need to update, just do `git pull gonum master` when you are on your master branch - do this before each new PR's branch is created.

Do take a note of the sha-1 of the HEAD of newfeature - this allows you to recover if things go terribly wrong (`0e1f7c64cf5940fd8f59ef0254e3913c9ee66b12` for reference). A final check that you can do is to `git diff origin/newfeature` since your remote newfeature branch should have no difference after the history manipulation, but rather just a change in the flow of events.

When you have a happy tree, this PR can be closed.

**Comment by kortschak** [comment]
Oh, and I forgot, when you think everything is OK (no diff between origin/newfeature, all clean etc), just do `git push -f origin newfeature`.

**Comment by Scorpiokat** [comment]
Sorry, I am a bit confused, as my master branch has not been automatically updated, so it used to be in the state when I started working on the issue (early October). So today I have updated it in accordance with the original master branch, and then sent all the commits. Looks like a challenge to bring all the changes back without ruining the fork. I'll try my best not to :)

**Comment by kortschak** [comment]
Yes, your github fork is a semi-independent entity, so keeping it up-to-date is a manual process of pulling the upstream HEAD (this is what the process of adding a tracking remote does). The approach I was suggesting of reseting `--hard` to the upstream remote rather than doing a pull will avoid the mess you see. That reset can be done no matter what state your master is in; what you are telling your local repo is "master should be at this sha, do it!".

Remember, you have at least two copies of your state, on your local machine and on github (plus anywhere else that has them). So if you damage your local, you can alway reset to the origin (github) state. If it comes to this, please ask for help first.

**Comment by Scorpiokat** [comment]
Dan @kortschak you are the best! Thanks for the guidance. That worked. I will try my best not to make that mistake happened in the future.
Rebased and sent the push request. Happily closing this PR.

**Comment by kortschak** [comment]
I'm glad I could help.

**Pull request closed without merging**
