### PR TITLE
all: define vg.FontExtents.Descent as a positive value to follow x/image/font/sfnt convention

### PR DESCRIPTION
**Pull request by sbinet**
Please take a look.

### CODE REVIEW

**Review by kortschak — COMMENTED** [review]
There is a reference to `Descent` in [vgpdf](https://github.com/gonum/plot/blob/f888cdb60200a6291af8763d83eda6c866a6f53d/vg/vgpdf/vgpdf.go#L185) that looks like it should change too.

**Comment by sbinet** [comment]
indeed, but IIRC, that's not the same `Descent`.
it's the one internal to `gofpdf`.

do you want me to add a comment about that?

**Comment by kortschak** [comment]
Sorry, no. My mistake.

**Review by kortschak — APPROVED** [review]

**Comment by sbinet** [comment]
it's finnicky business.

**Comment by kortschak** [comment]
Injudicious use of grep without following up with proper static analysis.

**Pull request merged**
