### PR TITLE
Add Thumbnail to bubbles.go. Solves #343

### PR DESCRIPTION
**Pull request by Bastiantheone**
I added a thumbnail function to bubbles.go. It shows a rectangle with the color of the bubble

### CODE REVIEW

**Comment by ctessum** [comment]
One issue here is that to be the most useful, a legend would include information about what size bubbles correspond to what z-values. My guess is that difficulty was why the thumbnail wasn't implemented originally.

One option would be to do something like [this](https://github.com/gonum/plot/blob/master/plotter/sankey.go#L420), to have a function that returned mutliple thumbnailers for several different size bubbles, as well as labels specifying what z-value each bubble size represents.

**Comment by Bastiantheone** [comment]
I created the issue, because I need a legend that explains which group each color bubble belongs. Would it be possible to add this function anyway?

**Comment by eaburns** [comment]
It seems fine to me to add it. Better some info than none.

**Comment by kortschak** [comment]
>One option would be to do something like this, to have a function that returned mutliple thumbnailers for several different size bubbles, as well as labels specifying what z-value each bubble size represents.

I like this.

**Pull request closed without merging**
