### PR TITLE
show the value of each bar on top of it.

### PR DESCRIPTION
**Pull request by ffhelicopter**
show the value of each bar on top of it.

#475

### CODE REVIEW

**Comment by ctessum** [comment]
Does this do anything that can't be done using the existing plotter.BarChart + plotter.Labels?

**Comment by agzuniverse** [comment]
This PR is relevant, and the contents help. Would be great if contributors could merge this in.

**Comment by kortschak** [comment]
As it stands, this cannot be merged since it does not pass tests.

**Comment by sbinet** [comment]
closing in favor of https://github.com/gonum/plot/pull/585

**Pull request closed without merging**
