### PR TITLE
plot: provide UnixTimeTicks

### LINKED ISSUE #136: Unix time tick marker
Original [issue 109](https://code.google.com/p/plotinum/issues/detail?id=109) created by eaburns on 2013-01-29T22:26:49.000Z:

It would be nice to have a tick marker that would interpret the data points as Unix time values and compute a nice set of ticks for them.

### PR DESCRIPTION
**Pull request by sbinet**
This CL provides a new plot.Ticker implementation, suitable for
time-based values.

Fixes #136.

### CODE REVIEW

**Comment by eaburns** [comment]
Thanks for doing this. Would it be possible to add a test and to post a sample image?

**Comment by sbinet** [comment]
sure: done.

**Comment by sbinet** [comment]
trying to figure out why travis sees a different time than on my machine...

**Comment by sbinet** [comment]
I have no clue.
The underlying `time.Time.Unix()` values are exactly the same...
Any idea?

**Comment by sbinet** [comment]
ah. I thought by using `time.UTC` I would be free of interesting time zone effects.
doesn't seem like so.
changed date format to only display `YYYY-MM-DD`.

**Comment by eaburns** [comment]
LGTM.

**Pull request merged**
