### PR TITLE
palette: add DivergingPalette interface

### PR DESCRIPTION
**Pull request by kortschak**
Formalise the notion already existing in the brewer package.

### CODE REVIEW

**Comment by eaburns** [comment]
I don't quite understand what a divergent pallet is; probably because I don't know what a critical index is. Mind giving a tiny bit of background?

**Comment by kortschak** [comment]
Where you have values that diverge from a zero/median point a diverging palette is useful. The critical index is the index into the palette for the colour(s) that represent that zero/median value.

**Comment by kortschak** [comment]
This will help (linked in the docs) http://colorbrewer.org/

**Comment by eaburns** [comment]
Got it! Thanks.
LGTM.

**Pull request merged**
