### PR TITLE
vg/draw: update Canvas.FillText signature for consistency

### LINKED ISSUE #274: draw: Canvas takes an x, y vg.Length pair in FillText
It looks like the vg.Length tuple => vg.Point change was missed here.

### PR DESCRIPTION
**Pull request by kortschak**
Fixes #274.

@sbinet @eaburns Please take a look.

### CODE REVIEW

**Comment by sbinet** [comment]
LGTM.

it would seem, there are 2 other occurrences of a pair `x,y vg.Length` which could be replaced by a `pt vg.Point`:
- https://github.com/gonum/plot/blob/master/legend.go#L37
- https://github.com/gonum/plot/blob/master/plotter/labels.go#L44
 
not sure whether these should be modified nor if they should be part of that CL.

**Comment by kortschak** [comment]
Not all x,y tuples are points. I'll wait for @eaburns.

**Comment by eaburns** [comment]
This change LGTM.
I think that it's fine to replace the offsets with points too.

**Comment by kortschak** [comment]
PTAL

**Comment by sbinet** [comment]
still LGTM

**Comment by sbinet** [comment]
(don't forget to rebase on top of the latest master)

**Pull request merged**
