### PR TITLE
travis: update test matrix

### PR DESCRIPTION
**Pull request by kortschak**
go1.5.2 -> go1.5.3
go1.6beta2 -> go1.6rc1

### CODE REVIEW

**Comment by btracey** [comment]
lgtm

Do we know why this failed?

**Comment by btracey** [comment]
I think it's travis being flaky, but it's down for me at the moment.

**Comment by kortschak** [comment]
vgx11 currently depends on coge.google.com, which no longer exists. Seb sent a PR to remove vgx11 from the tree which I've LGTM'd but which has not yet been merged.

**Comment by sbinet** [comment]
#241 has been merged.
please rebase, it should work now.

**Pull request merged**
