### PR TITLE
Fix tics when the maximum tic is negative.

### PR DESCRIPTION
**Pull request by btracey**
Fixes Issue #210.

### CODE REVIEW

**Comment by kortschak** [comment]
LGTM though tests on the tick generators (without plotting) would be nice.

**Comment by kortschak** [comment]
That's a very meta comment.

**Comment by btracey** [comment]
Submitting now to help fix the behavior.

How should the tests be done? I could test explicitly for the given values, but it seems like that would not be robust to changes in the tick selection mechanism.

**Comment by kortschak** [comment]
Our current tests for this are not robust to this, so I don't see this as worse. Fine to submit though.

**Pull request merged**
