### PR TITLE
plotutil: fix /main.go with no-err New plot function

### LINKED ISSUE #684: Outdated code in plotutil/main.go, doesn't compile
### What are you trying to do?

Run the plotutil sample program

### What did you do?

```
$ cd plotutil
$ go run main.go 
```

### What did you expect to happen?

Generate a plot

### What actually happened?

```
# command-line-arguments
./main.go:89:11: assignment mismatch: 2 variables but plot.New returns 1 values
./main.go:128:9: assignment mismatch: 2 variables but plot.New returns 1 values
```

### What version of Go and Gonum/plot are you using?

```
$ go version
go version go1.16 linux/amd64
$ git rev-parse HEAD
caab7788e04dfd7a74cec4ee80f55b7d1f9a2bfa
```
This is Gonum v0.9.0

### Does this issue reproduce with the current master?

Yes

### PR DESCRIPTION
**Pull request by Deleplace**
This fixes #684

### CODE REVIEW

**Comment by Deleplace** [comment]
Though this fixes the compile error, and runs without runtime errors, I do note that the produced files are small and maybe not what was originally expected: see attached.

example_errpoints
[example_errpoints.pdf](https://github.com/gonum/plot/files/6312543/example_errpoints.pdf)
example_errpoints
example_stackedAreaChart
[example_stackedAreaChart.pdf](https://github.com/gonum/plot/files/6312546/example_stackedAreaChart.pdf)
example_stackedAreaChart

**Comment by Deleplace** [comment]
I'm not sure I understand the "Error: golangci-lint exit with code 4"

This might be unrelated to my changes.

**Comment by kortschak** [comment]
Thank you for the contribution.

The golangci-lint error was just something getting stuck; I have restarted it and it competed successfully. You are correct about the size; in early versions of the API, save took size parameters in inches, but now takes them in points as a `vg.Length`. Changing them from 4 to `10*vg.Centimeter` would be the fix there.

@sbinet We have build minutes for Travis again, so they are filing due to Gio dependencies. Do you want to fix that in another PR?

**Comment by sbinet** [comment]
coming back to this (after a little Go hiatus).

it seems to me the `travis` build don't add real value compared to the GHA ones.
except perhaps for testing `go-tip`

perhaps just drop the other `travis` builds and just keep `go-tip`?

**Comment by sbinet** [comment]
(otherwise LGTM)

**Review by sbinet — APPROVED** [review]

**Comment by kortschak** [comment]
I'm happy to drop travis for plot. We need it on gonum/gonum since it tests numerical things that sometimes differ on arm64. The likelihood that we have breaking differences between arm64 and amd64 in plot is very low.

**Comment by sbinet** [comment]
https://github.com/gonum/plot/pull/701 is handling the "dropping Travis" part.

@Deleplace could you please send another PR against the [gonum/gonum](https://github.com/gonum/gonum) repo adding yourself to the `AUTHORS` and/or `CONTRIBUTORS` files?

thanks. (and apologies for the belated handling of that PR).

**Comment by Deleplace** [comment]
Thank you Sebastien

**Comment by sbinet** [comment]
needs https://github.com/gonum/gonum/pull/1650

**Comment by kortschak** [comment]
@Deleplace Welcome.

**Pull request merged**
