### PR TITLE
Fixed vgimg origin to match other backends

### PR DESCRIPTION
**Pull request by ctessum**

### CODE REVIEW

**Comment by kortschak** [comment]
Is there a bug this is fixing?

On line 60 s/0./0/

**Comment by dgryski** [comment]
@kortschak bug introduced in https://github.com/gonum/plot/pull/26

**Comment by kortschak** [comment]
Thanks, @dgryski.

@ctessum, please add to the commit message that this fixes a bug that was uncovered by #26.

Some kind of test would be good too.

**Comment by ctessum** [comment]
I'm not sure how to add a test that doesn't require visual inspection for this.

**Comment by kortschak** [comment]
We can cope with a small png.

**Comment by kortschak** [comment]
Closing because we have a competing proposal with a test in #182.

**Pull request closed without merging**
