### PR TITLE
vg/vgtex: add test against golden file

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by eaburns** [comment]
Should this commit also add the golden file?

**Comment by sbinet** [comment]
actually, it's already there: https://github.com/gonum/plot/blob/master/vg/vgtex/testdata/scatter_golden.tex
(I forgot to add the remaining plumbing to the original `vg/vgtex` PR)

**Comment by eaburns** [comment]
LGMT.

**Comment by sbinet** [comment]
(ah! you've corrected your earlier "LGMT". I was about to be facetious and post: https://twitter.com/bradfitz/status/718938439010295810 :P)

**Pull request merged**
