### PR TITLE
all: update jpg/png/tiff reference files

### PR DESCRIPTION
**Pull request by sbinet**
This CL updates the PNG, JPG and TIFF reference files after the glyph
kerning fix went into llgcode/draw2d:
 https://github.com/llgcode/draw2d/pull/120

### CODE REVIEW

**Comment by sbinet** [comment]
this fixes the build (yay!)
kerning looks better too :)

**Comment by eaburns** [comment]
Thanks! I'm on mobile so I can't see the old and new images side by side. If they look good to you, I'd say to just merge it. This has been broken too long.

**Comment by kortschak** [comment]
What happened there?

**Comment by sbinet** [comment]
not sure.
I rebased my local master on top of my local draw2d-glyphs branch.
pushed master to origin.
then, as this PR wasn't automatically closed, I also pushed my local draw2d-glyphs to my github repo.
then, the PR was automatically closed.

(that was before my first (Monday!) morning coffee, though...)

I usually do the reverse.

**Pull request closed without merging**
