### PR TITLE
travis: add go-1.10.x

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by decibelcooper** [comment]
https://github.com/travis-ci/gimme/issues/132

I'm still getting 1.7.4

**Comment by sbinet** [comment]
yeah, we need for https://github.com/travis-ci/gimme/pull/130 to go in before being (maybe?) able to use the `1.10.x` syntax.

**Comment by kortschak** [comment]
The gimme error is fixed as demonstrated by the failure found in labelling_test.go.

PTAL

**Comment by decibelcooper** [comment]
Yep, https://travis-ci.org/gonum/plot/jobs/344614350#L440

**Pull request merged**
